import Modals from "@/components/modals";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "@/utils/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="min-h-screen max-w-screen flex">
      <body
        className={`flex-1 flex bg-gray-100 text-gray-400 ${inter.className}`}
      >
        <Provider>
          {children}
          <Modals />
        </Provider>
      </body>
    </html>
  );
}
